### ISSUE TITLE
Bezirk not able to deserialize Events which has registered subtypes

### ISSUE THREAD

**Issue by ascoril** [Bezirk-Bosch/Middleware#132]
registration of subtypes is done as:

**`Option:`**

```
package com.bezirk.u.util;

import java.io.Serializable;

public interface Option extends Serializable {

    public int getOptionScore();

    public void setOptionScore(int optionScore) ;

    public String getId();

    public void setId(String id);

    public String getName();

    public void setName(String name);

    public String getOptionType();

    public void setOptionType(String type);

    public String getOptionTypeId();

    public void setOptionTypeId(String optionTypeId);

}
```

**OPDOption**

```
`package com.bezirk.u.util;

import com.opencsv.bean.CsvBindByName;

/**
 * A concrete implementation of the Option interface based on the open data
 */
public class OPDOption implements Option{

    @CsvBindByName(column = "GTIN Code")
    private String id;
    @CsvBindByName(column = "GTIN Name")
    private String name;
    @CsvBindByName(column = "Segmentation (GPC)")
    private String optionType;
    @CsvBindByName(column = "GPC Segmentation Code")
    private String optionTypeId;
    @CsvBindByName(column = "GTIN Image")
    private String gtinImage;

    private int optionScore = 0;

    @Override
    public int getOptionScore() {
        return optionScore;
    }

    @Override
    public void setOptionScore(int optionScore) {
        this.optionScore = optionScore;
    }

    @Override
    public String getId() {
        return id;
    }

    @Override
    public void setId(String id) {
         this.id = UUtil.getInstance().getBezirkUri() + "gtin/" + id;
    }

    @Override
    public String getName() {
        return name;
    }

    @Override
    public void setName(String name) {
       this.name = name;
    }

    @Override
    public String getOptionType() {
        return optionType;
    }

    @Override
    public void setOptionType(String optionType) {
        this.optionType = optionType;
    }

    @Override
    public String getOptionTypeId() {
        return optionTypeId;
    }

    @Override
    public void setOptionTypeId(String optionTypeId) {
        this.optionTypeId = UUtil.getInstance().getBezirkUri() + "gpc/" + optionTypeId;
    }

    public String getGtinImage() {
        return gtinImage;
    }

    public void setGtinImage(String gtinImage) {
        this.gtinImage = gtinImage;
    }
}
`
```

and Choose Event as:

```
`package com.bezirk.beyond.protocols;

import com.bezirk.middleware.messages.Event;
import com.bezirk.middleware.messages.Message;
import com.google.gson.GsonBuilder;
import com.bezirk.u.util.Option;

import java.util.Set;

import gson.typeadapters.RuntimeTypeAdapterFactory;

/**
 *
 */
public class Choose extends Event {

    static {
        GsonBuilder builder = new GsonBuilder();
        RuntimeTypeAdapterFactory<Option> interfaceAdapter = RuntimeTypeAdapterFactory.of(Option.class);
        interfaceAdapter.registerSubtype(OPDOption.class);
        builder.registerTypeAdapterFactory(interfaceAdapter);
        Message.setGsonBuilder(builder);
    }

    private Set<Option> options;
    private String user;

    public Set<Option> getOptions() {
        return options;
    }

    public void setOptions(Set<Option> options) {
        this.options = options;

    }

    public void addOption(Option option) {
        this.options.add(option);
    }

    public String getUser() {
        return user;
    }

    public void setUser (String user) {
        this.user = user;
    }
}`
```

crashes with:

```
`java.lang.RuntimeException: Unable to start receiver com.bezirk.middleware.android.ZirkMessageReceiver: java.lang.RuntimeException: Unable to invoke no-args constructor for interface com.bezirk.u.util.Option. Register an InstanceCreator with Gson for this type may fix this problem.
                                                                               at android.app.ActivityThread.handleReceiver(ActivityThread.java:2732)
                                                                               at android.app.ActivityThread.-wrap14(ActivityThread.java)
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                               at android.os.Looper.loop(Looper.java:148)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                            Caused by: java.lang.RuntimeException: Unable to invoke no-args constructor for interface com.bezirk.u.util.Option. Register an InstanceCreator with Gson for this type may fix this problem.
                                                                               at com.google.gson.internal.ConstructorConstructor$14.construct(ConstructorConstructor.java:226)
                                                                               at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:210)
                                                                               at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
                                                                               at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
                                                                               at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
                                                                               at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
                                                                               at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
                                                                               at com.google.gson.Gson.fromJson(Gson.java:887)
                                                                               at com.google.gson.Gson.fromJson(Gson.java:952)
                                                                               at com.google.gson.Gson.fromJson(Gson.java:925)
                                                                               at com.bezirk.middleware.messages.Message$InterfaceAdapter.deserialize(Message.java:122)
                                                                               at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
                                                                               at com.google.gson.Gson.fromJson(Gson.java:887)
                                                                               at com.google.gson.Gson.fromJson(Gson.java:852)
                                                                               at com.google.gson.Gson.fromJson(Gson.java:801)
                                                                               at com.google.gson.Gson.fromJson(Gson.java:773)
                                                                               at com.bezirk.middleware.messages.Message.fromJson(Message.java:91)
                                                                               at com.bezirk.middleware.android.ZirkMessageReceiver.processEvent(ZirkMessageReceiver.java:69)
                                                                               at com.bezirk.middleware.android.ZirkMessageReceiver.onReceive(ZirkMessageReceiver.java:41)
                                                                               at android.app.ActivityThread.handleReceiver(ActivityThread.java:2725)
                                                                               at android.app.ActivityThread.-wrap14(ActivityThread.java) 
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                               at android.os.Looper.loop(Looper.java:148) 
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                            Caused by: java.lang.UnsupportedOperationException: Interface can't be instantiated! Interface name: com.bezirk.u.util.Option
                                                                               at com.google.gson.internal.UnsafeAllocator.assertInstantiable(UnsafeAllocator.java:117)
                                                                               at com.google.gson.internal.UnsafeAllocator.access$000(UnsafeAllocator.java:31)
                                                                               at com.google.gson.internal.UnsafeAllocator$1.newInstance(UnsafeAllocator.java:49)
                                                                               at com.google.gson.internal.ConstructorConstructor$14.construct(ConstructorConstructor.java:223)
                                                                               at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:210) 
                                                                               at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) 
                                                                               at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82) 
                                                                               at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61) 
                                                                               at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129) 
                                                                               at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220) 
                                                                               at com.google.gson.Gson.fromJson(Gson.java:887) 
                                                                               at com.google.gson.Gson.fromJson(Gson.java:952) 
                                                                               at com.google.gson.Gson.fromJson(Gson.java:925) 
                                                                               at com.bezirk.middleware.messages.Message$InterfaceAdapter.deserialize(Message.java:122) 
                                                                               at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) 
                                                                              at com.google.gson.Gson.fromJson(Gson.java:887) 
                                                                               at com.google.gson.Gson.fromJson(Gson.java:852) 
                                                                               at com.google.gson.Gson.fromJson(Gson.java:801) 
                                                                               at com.google.gson.Gson.fromJson(Gson.java:773) 
                                                                               at com.bezirk.middleware.messages.Message.fromJson(Message.java:91) 
                                                                               at com.bezirk.middleware.android.ZirkMessageReceiver.processEvent(ZirkMessageReceiver.java:69) 
                                                                               at com.bezirk.middleware.android.ZirkMessageReceiver.onReceive(ZirkMessageReceiver.java:41) 
                                                                               at android.app.ActivityThread.handleReceiver(ActivityThread.java:2725) 
                                                                               at android.app.ActivityThread.-wrap14(ActivityThread.java) 
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                               at android.os.Looper.loop(Looper.java:148) 
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

`

**Comment by rishabhgulati** [comment]
Closing this issue as `setGsonBuilder()` in [Message](https://github.com/Bezirk-Bosch/Middleware/blob/master/core/bezirk-middleware-api/src/main/java/com/bezirk/middleware/messages/Message.java) provides a mechanism to pass a GsonBuilder (with custom `RuntimeTypeAdapterFactory`)

**Comment by ascoril** [comment]
static {
        GsonBuilder builder = new GsonBuilder();
        RuntimeTypeAdapterFactory<ChoiceEntity> interfaceAdapter = RuntimeTypeAdapterFactory.of(ChoiceEntity.class);
        interfaceAdapter.registerSubtype(OPDChoiceEntity.class).registerSubtype(AutoAppChoiceEntity.class).registerSubtype(ContactChoiceEntity.class);
        builder.registerTypeAdapterFactory(interfaceAdapter);
        Message.setGsonBuilder(builder);
    }

Strill OPDCHoiceEntity is not getting deserialized as part of ChoiceObservationCollection result:

**Comment by rishabhgulati** [comment]
@ascoril How do i replicate this?

**Comment by ascoril** [comment]
@rishabhgulati .... you can use 

https://github.com/Bezirk-Bosch/Personalization/blob/integration/protocol/protocol-beyond/src/main/java/com/bezirk/beyond/protocols/TestBeyond.java 

to send the ChoiceObservationCollection, you can verify that each ChoiceObservation has an OPDChoiceEntity as the result.

You can run beyondapp from https://github.com/Bezirk-Bosch/Personalization/tree/integration/Beyond/ui/beyondapp and click on start bezirk, then put a debug point at the https://github.com/Bezirk-Bosch/Personalization/blob/integration/Beyond/beyondzirk-android/src/main/java/com/bezirk/beyond/messagehandler/BeyondMessageHandler.java method processChoiceObservationCollection to see that the result of each ChoiceObservation has been stripped off from OPDChoiceEntity to ChoiceEntity.

**Comment by rishabhgulati** [comment]
@ascoril 
Firstly, this link is broken
https://github.com/Bezirk-Bosch/Personalization/blob/integration/protocol/protocol-beyond/src/main/java/com/bezirk/beyond/protocols/TestBeyond.java

In BeyondZirk.java
This is the event set being used
```
EventSet beyondEventSet = new EventSet(Choose.class, ChooseWithOptionTypes.class, OPDChoiceObservationCollection.class,
                AutoAppChoiceObservationCollection.class, ContactChoiceObservationCollection.class);
```

GsonBuilder is being set several times statically in different event subclasses. This would replace the GsonBuilder in the `Message` class each time. For instance in `OPDChoiceObservationCollection`
```
static {
        GsonBuilder builder = new GsonBuilder();
        RuntimeTypeAdapterFactory interfaceAdapter = RuntimeTypeAdapterFactory.of(ChoiceEntity.class);
        interfaceAdapter.registerSubtype(OPDChoiceEntity.class).registerSubtype(AutoAppChoiceEntity.class).registerSubtype(ContactChoiceEntity.class);
        builder.registerTypeAdapterFactory(interfaceAdapter);
        Message.setGsonBuilder(builder);
    }
```

In `ChooseWithOptionTypes`
```
static {
        GsonBuilder builder = new GsonBuilder();
        RuntimeTypeAdapterFactory interfaceAdapter = RuntimeTypeAdapterFactory.of(Option.class);
        interfaceAdapter.registerSubtype(OPDOption.class);
        builder.registerTypeAdapterFactory(interfaceAdapter);
        Message.setGsonBuilder(builder);
    }
```

You can instead create all `RuntimeTypeAdapterFactory`s and set the GsonBuilder

**Comment by ascoril** [comment]
@rishabhgulati, `OPDChoiceObservationCollection` is made changes yesterday to conform to proto-buf schema , so it can be handled without the `RuntimeTypeAdapterFactory` working (thought i would proceed with a different approach in parallel till this issue is fixed). To replicate the issue, the file contents till the commit: 0b42c57ac43f6ac290aae5e203245b5e9a08115e should be used

TestBeyond:
https://github.com/Bezirk-Bosch/Personalization/blob/0b42c57ac43f6ac290aae5e203245b5e9a08115e/protocol/protocol-beyond/src/main/java/com/bezirk/beyond/protocols/TestBeyond.java

`ChoiceObservationCollection`
https://github.com/Bezirk-Bosch/Personalization/blob/0b42c57ac43f6ac290aae5e203245b5e9a08115e/protocol/protocol-beyond/src/main/java/com/bezirk/beyond/protocols/ChoiceObservationCollection.java

`BeyondZirk`
https://github.com/Bezirk-Bosch/Personalization/blob/0b42c57ac43f6ac290aae5e203245b5e9a08115e/Beyond/beyondzirk-android/src/main/java/com/bezirk/beyond/BeyondZirk.java

Also, `ChooseWIthOptionTypes` as in https://github.com/Bezirk-Bosch/Personalization/blob/0b42c57ac43f6ac290aae5e203245b5e9a08115e/protocol/protocol-beyond/src/main/java/com/bezirk/beyond/protocols/ChooseWithOptionTypes.java doesn't get instantiated in the observe flow, so there is only one RuntimeTypeAdapterFactory which gets set as in the `ChoiceObservationCollection`
