### ISSUE TITLE
RejectedExecutionException while sending message and minimizing app at the same time

### ISSUE THREAD

**Issue by maass-bezirk** [Bezirk-Bosch/Middleware#157]
Not sure the minimizing part actually matters, but here is a stack trace to fix it in any case:

E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.bosch.party, PID: 12440
                  java.lang.RuntimeException: Unable to start service com.bezirk.middleware.android.ComponentManager@2549693 with Intent { act=MULTICAST_EVENT cmp=com.bosch.party/com.bezirk.middleware.android.ComponentManager (has extras) }: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@1b8ccacd rejected from java.util.concurrent.ThreadPoolExecutor@84aff82[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 3]
                      at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2913)
                      at android.app.ActivityThread.access$2100(ActivityThread.java:153)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1403)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:135)
                      at android.app.ActivityThread.main(ActivityThread.java:5286)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:372)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1384)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1179)
                   Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@1b8ccacd rejected from java.util.concurrent.ThreadPoolExecutor@84aff82[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 3]
                      at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2011)
                      at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
                      at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
                      at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:81)
                      at java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:593)
                      at com.bezirk.middleware.android.proxy.android.AndroidProxyServer.sendEventUsingExecutor(AndroidProxyServer.java:151)
                      at com.bezirk.middleware.android.proxy.android.AndroidProxyServer.sendMulticastEvent(AndroidProxyServer.java:94)
                      at com.bezirk.middleware.android.ActionProcessor.processSendActions(ActionProcessor.java:134)
                      at com.bezirk.middleware.android.ActionProcessor.processBezirkAction(ActionProcessor.java:67)
                      at com.bezirk.middleware.android.ComponentManager.onStartCommand(ComponentManager.java:92)
                      at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2896)
                      at android.app.ActivityThread.access$2100(ActivityThread.java:153) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1403) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:135) 
                      at android.app.ActivityThread.main(ActivityThread.java:5286) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:372) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1384) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1179)

**Comment by maass-bezirk** [comment]
This is also happening when swiping the app away in the task list (Neha found this).

**Comment by maass-bezirk** [comment]
This was fixed by the iBinder refactoring for 3.1.0.
