### ISSUE TITLE
NetworkOnMainThreadException

### ISSUE THREAD

**Issue by punithmailme** [Bezirk-Bosch/Middleware#169]
Steps:

1.	Open Bezirk Test Application
2.	Open Advanced Bezirk Test
3.	On Device A : Start Subscriber
4.	On Device B : Start Publisher
5.	Within few seconds App will crash.

If above steps does not give a crash, do “Stop Bezirk Middleware” and perform the above steps again. Publisher device app will crash with below stacktrace.

```
com.bezirk.middleware.android.testApp E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.bezirk.middleware.android.testApp, PID: 27363
java.lang.RuntimeException: Unable to start receiver com.bezirk.middleware.android.ZirkMessageReceiver: android.os.NetworkOnMainThreadException
   at android.app.ActivityThread.handleReceiver(ActivityThread.java:2732)
   at android.app.ActivityThread.-wrap14(ActivityThread.java)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421)
   at android.os.Handler.dispatchMessage(Handler.java:102)
   at android.os.Looper.loop(Looper.java:148)
   at android.app.ActivityThread.main(ActivityThread.java:5417)
   at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: android.os.NetworkOnMainThreadException
   at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1273)
   at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:269)
   at libcore.io.IoBridge.sendto(IoBridge.java:523)
   at java.nio.SocketChannelImpl.writeImpl(SocketChannelImpl.java:403)
   at java.nio.SocketChannelImpl.write(SocketChannelImpl.java:361)
   at java.nio.PipeImpl$PipeSinkChannel.write(PipeImpl.java:114)
   at zmq.Signaler.send(Signaler.java:121)
   at zmq.Mailbox.send(Mailbox.java:85)
   at zmq.Ctx.sendCommand(Ctx.java:388)
   at zmq.ZObject.sendCommand(ZObject.java:362)
   at zmq.ZObject.sendActivateRead(ZObject.java:214)
   at zmq.Pipe.flush(Pipe.java:281)
   at zmq.LB.send(LB.java:126)
   at zmq.Dealer.xsend(Dealer.java:74)
   at zmq.SocketBase.send(SocketBase.java:609)
   at org.zeromq.ZMQ$Socket.send(ZMQ.java:1302)
   at org.zeromq.ZMQ$Socket.send(ZMQ.java:1291)
   at com.bezirk.middleware.core.comms.Sender.send(Sender.java:101)
   at com.bezirk.middleware.core.comms.Peer.send(Peer.java:136)
   at com.bezirk.middleware.core.comms.JmqCommsManager.sendToOne(JmqCommsManager.java:61)
   at com.bezirk.middleware.core.comms.processor.CommsProcessor.sendEventLedger(CommsProcessor.java:287)
   at com.bezirk.middleware.core.pubsubbroker.PubSubBroker.sendUnicastEvent(PubSubBroker.java:315)
   at com.bezirk.middleware.core.proxy.ProxyServer.sendEvent(ProxyServer.java:71)
   at com.bezirk.middleware.android.ProxyClient.sendEvent(ProxyClient.java:208)
   at com.bezirk.middleware.android.AdvancedTestActivity$5.receiveEvent(AdvancedTestActivity.java:146)
   at com.bezirk.middleware.android.ZirkMessageReceiver.processEvent(ZirkMessageReceiver.java:111)
   at com.bezirk.middleware.android.ZirkMessageReceiver.onReceive(ZirkMessageReceiver.java:67)
   at android.app.ActivityThread.handleReceiver(ActivityThread.java:2725)
   at android.app.ActivityThread.-wrap14(ActivityThread.java) 
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421) 
   at android.os.Handler.dispatchMessage(Handler.java:102) 
   at android.os.Looper.loop(Looper.java:148) 
   at android.app.ActivityThread.main(ActivityThread.java:5417) 
   at java.lang.reflect.Method.invoke(Native Method) 
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616

```

**Comment by punithmailme** [comment]
Tested and merged to feature/clean-stream branch.
It is working fine.
