### ISSUE TITLE
Middleware PC (3.0.2-3) crashing after sending 5000 events continously

### ISSUE THREAD

**Issue by ascoril** [Bezirk-Bosch/Middleware#172]
Bezirk PC (3.0.2-3) crashing after sending 5000 events continously also it is unpredictable, sometimes it is crashing just after sending 1000 events

Rows processed: 21465
ChoiceObservationCollection: com.bezirk.beyond.protocols.ChoiceObservationCollection@31c56721
Number of observations sent: 5498
Rows processed: 21466
ChoiceObservationCollection: com.bezirk.beyond.protocols.ChoiceObservationCollection@7e451790
Number of observations sent: 5499
Rows processed: 21467
ChoiceObservationCollection: com.bezirk.beyond.protocols.ChoiceObservationCollection@3f71ae7f
Number of observations sent: 5500
Exception in thread "main" java.nio.channels.ClosedSelectorException
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:83)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at zmq.Signaler.waitEvent(Signaler.java:148)
	at zmq.Mailbox.recv(Mailbox.java:105)
	at zmq.SocketBase.processCommands(SocketBase.java:796)
	at zmq.SocketBase.send(SocketBase.java:634)
	at org.zeromq.ZMQ$Socket.send(ZMQ.java:1302)
	at org.zeromq.ZMQ$Socket.send(ZMQ.java:1291)
	at com.bezirk.middleware.core.comms.Sender.sendMsg(Sender.java:176)
	at com.bezirk.middleware.core.comms.Sender.send(Sender.java:106)
	at com.bezirk.middleware.core.comms.Peer.send(Peer.java:124)
	at com.bezirk.middleware.core.comms.JmqCommsManager.sendToAll(JmqCommsManager.java:53)
	at com.bezirk.middleware.core.comms.processor.CommsProcessor.sendEventLedger(CommsProcessor.java:298)
	at com.bezirk.middleware.core.pubsubbroker.PubSubBroker.sendMulticastEvent(PubSubBroker.java:254)
	at com.bezirk.middleware.core.proxy.ProxyServer.sendEvent(ProxyServer.java:57)
	at com.bezirk.middleware.java.proxy.ProxyClient.sendEvent(ProxyClient.java:188)
	at com.bezirk.middleware.java.proxy.ProxyClient.sendEvent(ProxyClient.java:183)
	at com.bezirk.beyond.protocols.TestBeyond.main(TestBeyond.java:125)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

**Comment by rishabhgulati** [comment]
Are you looping through something and sending the events without a gap? Whats the use case here?

**Comment by ascoril** [comment]
The use-case is to use bezirk as tool for bench-marking beyond.  We have a data-set of 500,000 transaction history against which beyond needs to be benchmarked. 
Since loading the 500,000 data-set  through app is not possible. To use bezirk and have a zirk running in PC to feed the data to beyond. There cannot be any gap between each event sent, otherwise benchmarking data will not stand up to the expectation.

**Comment by rishabhgulati** [comment]
This looks like a use case for streaming instead. Sending 500,000 events with bezirk without a realistic interval is not feasible and is definitely not the right use of the middleware events. You would either need to club these transactions into a fewer number of event or use streaming instead.

**Comment by ascoril** [comment]
Is the bezirk streaming ready in the current version ?

**Comment by ascoril** [comment]
I have analysed and saw, if there is no consumer available then bezirk is able to send the whole set of events. If the consumer number increases, then the events that bezirk is capable of sending decreases and ultimately crashing with the exception as above. To test the following system can be used:

Producer (in PC)
https://github.com/Bezirk-Bosch/Personalization/blob/integration/protocol/protocol-beyond/src/main/java/com/bezirk/beyond/protocols/TestBeyond.java

Consumer in Android
https://github.com/Bezirk-Bosch/Personalization/tree/integration/Beyond/ui/beyondapp

You can have multiple instances of beyondapp running in different android devices

**Comment by ascoril** [comment]
Is there any improvements available for this issue?

**Comment by SurajPandurangaJannu** [comment]
Error at the consumer side:

01-02 14:03:29.762 1045-1077/? E/ActivityManager: ANR in com.bezirk.beyond.beyondapp
                                                  PID: 11598
                                                  Reason: Broadcast of Intent { act=com.bezirk.middleware.broadcast flg=0x10000010 cmp=com.bezirk.beyond.beyondapp/com.bezirk.middleware.android.ZirkMessageReceiver (has extras) }
                                                  Load: 0.0 / 0.0 / 0.0
                                                  CPU usage from 41708ms to 0ms ago (2017-01-02 14:02:46.975 to 2017-01-02 14:03:28.683) with 99% awake:
                                                    123% 11598/com.bezirk.beyond.beyondapp: 114% user + 8.3% kernel / faults: 157064 minor
                                                    5.6% 560/adbd: 1.3% user + 4.2% kernel / faults: 2379 minor
                                                    5.1% 13254/com.xuecs.sqlitemanager: 4.3% user + 0.7% kernel / faults: 4870 minor
                                                    4.6% 1045/system_server: 2.3% user + 2.2% kernel / faults: 2140 minor
                                                    4.4% 5861/com.estrongs.android.pop: 3% user + 1.4% kernel / faults: 936 minor
                                                    3.9% 435/logd: 0.7% user + 3.2% kernel / faults: 14 minor
                                                    3.4% 1443/sdcard: 0.2% user + 3.1% kernel
                                                    2.3% 6227/logcat: 0.9% user + 1.3% kernel / faults: 1 minor
                                                    2.3% 6369/logcat: 1.1% user + 1.1% kernel / faults: 1 minor
                                                    1.1% 7820/kworker/1:0: 0% user + 1.1% kernel
                                                    1% 14331/kworker/u8:4: 0% user + 1% kernel
                                                    0.9% 532/surfaceflinger: 0.4% user + 0.5% kernel
                                                    0.8% 11630/kworker/u8:9: 0% user + 0.8% kernel
                                                    0.6% 5985/.esfm: 0.4% user + 0.2% kernel / faults: 165 minor
                                                    0.6% 7/rcu_preempt: 0% user + 0.6% kernel
                                                    0.5% 11635/kworker/u8:10: 0% user + 0.5% kernel
                                                    0.2% 109/kswapd0: 0% user + 0.2% kernel
                                                    0.4% 536/kschedfreq:0: 0% user + 0.4% kernel
                                                    0.4% 3/ksoftirqd/0: 0% user + 0.4% kernel
                                                    0.4% 4288/kschedfreq:2: 0% user + 0.4% kernel
                                                    0.3% 41/smem_native_rpm: 0% user + 0.3% kernel
                                                    0.3% 32523/VosMCThread: 0% user + 0.3% kernel
                                                    0.3% 12/ksoftirqd/1: 0% user + 0.3% kernel
                                                    0.3% 8377/kworker/0:3: 0% user + 0.3% kernel
                                                    0.3% 8901/kworker/3:0: 0% user + 0.3% kernel
                                                    0.2% 8388/kworker/0:5: 0% user + 0.2% kernel
                                                    0.2% 430/jbd2/sda35-8: 0% user + 0.2% kernel
                                                    0.1% 1956/com.google.android.gms.persistent: 0% user + 0% kernel / faults: 75 minor
                                                    0.2% 318/nanohub: 0% user + 0.2% kernel
                                                    0.1% 8009/mdss_fb0: 0% user + 0.1% kernel
                                                    0.1% 8391/kworker/1:2: 0% user + 0.1% kernel
                                                    0.1% 259/irq/480-synapti: 0% user + 0.1% kernel
                                                    0.1% 529/msm_irqbalance: 0% user + 0.1% kernel
                                                    0.1% 539/irq/19-408000.q: 0% user + 0.1% kernel
                                                    0.1% 566/thermal-engine: 0% user + 0% kernel / faults: 6 minor
                                                    0% 572/perfd: 0% user + 0% kernel / faults: 4 minor
                                                    0% 1472/com.android.systemui: 0% user + 0% kernel / faults: 7 minor
                                                    0% 20/ksoftirqd/3: 0% user + 0% kernel
                                                    0% 7788/kworker/2:1: 0% user + 0% kernel
                                                    0% 8/rcu_sched: 0% user + 0% kernel
                                                    0% 16/ksoftirqd/2: 0% user + 0% kernel
                                                    0% 240/spi6: 0% user + 0% kernel
                                                    0% 575/audioserver: 0% user + 0% kernel / faults: 6 minor
                                                    0% 1994/com.google.android.gms: 0% user + 0% kernel / faults: 3 minor
                                                    0% 7904/kworker/2:2: 0% user + 0% kernel
                                                    0% 14755/kworker/2:3: 0% user + 0% kernel
                                                    0% 11/migration/1: 0% user + 0% kernel
                                                    0% 45/irq/260-cpr3: 0% user + 0% kernel
                                                    0% 316/irq/478-nanohub: 0% user + 0% kernel
                                                    0% 397/kworker/2:1H: 0% user + 0% kernel
                                                    0% 463/kworker/0:2H: 0% user + 0% kernel
                                                    0% 525/healthd: 0% user + 0% kernel
                                                    0% 530/lmkd: 0% user + 0% kernel
                                                    0% 531/servicemanager: 0% user + 0% kernel
                                                    0% 593/cnss-daemon: 0% user + 0% kernel
                                                    0% 2126/com.quicinc.cne.CNEService: 0% user + 0% kernel / faults: 8 minor
                                                    0% 5586/com.google.android.googlequicksearchbox:search: 0% user + 0% kernel / faults: 48 minor
                                                    0% 11585/kworker/1:5: 0% user + 0% kernel
                                                    0% 32521/wlan_logging_th: 0% user + 0% kernel
                                                    0% 32528/wpa_supplicant: 0% user + 0% kernel
                                                  44% TOTAL: 33% user + 8% kernel + 0.2% iowait + 1.4% irq + 0.9% softirq
                                                  CPU usage from 60043962ms to 60043962ms ago (1970-01-01 05:30:00.000 to 1970-01-01 05:30:00.000) with 0% awake:
                                                  0% TOTAL: 0% user + 0% kernel
01-02 14:03:30.000 1045-1080/? E/libprocessgroup: failed to kill 1 processes for processgroup 11598
01-02 14:03:30.227 1045-1324/? E/InputDispatcher: channel 'ee212ce com.bezirk.beyond.beyondapp/com.bezirk.beyond.beyondapp.BeyondAppActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
01-02 14:03:31.371 16643-16643/? E/com.bezirk.middleware.android.ZirkMessageReceiver: 14:03:31.369 [ERROR] ZirkMessageReceiver - Application is not started

**Comment by SurajPandurangaJannu** [comment]
Another error with 1ms delay between the events:

```
01-02 14:37:41.630 19415-19458/? E/AndroidRuntime: FATAL EXCEPTION: pool-6-thread-3
                                                   Process: com.bezirk.beyond.beyondapp, PID: 19415
                                                   java.lang.OutOfMemoryError: Failed to allocate a 84328 byte allocation with 20296 free bytes and 19KB until OOM
                                                       at java.util.Arrays.copyOf(Arrays.java:3231)
                                                       at java.util.Arrays.copyOf(Arrays.java:3204)
                                                       at java.util.ArrayList.grow(ArrayList.java:249)
                                                       at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:223)
                                                       at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:215)
                                                       at java.util.ArrayList.add(ArrayList.java:441)
                                                       at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:73)
                                                       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
                                                       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
                                                       at com.google.gson.Gson.fromJson(Gson.java:887)
                                                       at com.google.gson.Gson.fromJson(Gson.java:852)
                                                       at com.google.gson.Gson.fromJson(Gson.java:801)
                                                       at com.google.gson.Gson.fromJson(Gson.java:773)
                                                       at com.bezirk.middleware.core.comms.processor.WireMessage.deserialize(WireMessage.java:125)
                                                       at com.bezirk.middleware.core.comms.processor.CommsProcessor$ProcessIncomingMessage.run(CommsProcessor.java:570)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                       at java.lang.Thread.run(Thread.java:761)
```

**Comment by rishabhgulati** [comment]
@ascoril The commit you pointed out is not building for me. Should i try it with the integration branch?
Where do I get this `online_retail_data.csv` file from?(used in TestBeyond)
`final InputStream insORD = new FileInputStream(new File("D:\\Bezirk-code\\U-new\\Personalization\\Beyond\\ui\\beyondapp\\src\\main\\res\\raw\\online_retail_data.csv"));
            `

**Comment by ascoril** [comment]
@rishabhgulati .... for this issue, you can use the latest integration branch. The csv is available at: https://github.com/Bezirk-Bosch/Personalization/blob/integration/dataset/online_retail_data.csv .... once you checkout integration you will see the dataset folder.
