### ISSUE TITLE
Bezirk-PC Unable to load features.properties file from classpath. 

### ISSUE THREAD

**Issue by punithmailme** [Bezirk-Bosch/Middleware#98]
Fails at runtime only for Bezirk-PC version,  Unable to find features.properties in resources folder of commons project 

```
16:05:38.872 [main] ERROR com.bezirk.comms.CommsFeature - Unable to load features.properties file from classpath.
java.lang.NullPointerException: null
	at java.util.Properties$LineReader.readLine(Properties.java:434) ~[na:1.8.0_76-release]
	at java.util.Properties.load0(Properties.java:353) ~[na:1.8.0_76-release]
	at java.util.Properties.load(Properties.java:341) ~[na:1.8.0_76-release]
	at com.bezirk.comms.CommsFeature.init(CommsFeature.java:38) [main/:na]
	at com.bezirk.comms.CommsFeature.isActive(CommsFeature.java:58) [main/:na]
	at com.bezirk.comms.CommsFactory.getActiveComms(CommsFactory.java:49) [main/:na]
	at com.bezirk.starter.MainService.initComms(MainService.java:339) [main/:na]
	at com.bezirk.starter.MainService.startStack(MainService.java:229) [main/:na]
	at com.bezirk.middleware.proxy.Proxy.<init>(Proxy.java:59) [main/:na]
	at com.bezirk.middleware.proxy.Factory.registerZirk(Factory.java:19) [main/:na]
	at test.Test.<init>(Test.java:29) [main/:na]

```

**Comment by rishabhgulati** [comment]
7138eb0614a693d3002d83cf6ec993394b349d2e should fix this.
